### ISSUE TITLE
v6 ROADMAP

### ISSUE THREAD

**Issue by jaredallard** [NodeMC/NodeMC#1]
Hello everyone! Here's our projected roadmap of things that need to be implemented for the v6 release! :+1: 

Feel free to discuss the proposed changes and/or add some changes, in the Discord, or in this issue thread.

**CORE**

* [ ] Implement the API spec in [CORE/docs](https://github.com/NodeMC/CORE/tree/master/docs)
* [ ] Metrics Aggregation
* [ ] Websockets / socket.io for realtime data.
* [ ] *optional* Basic SSO support
* [ ] Document Auth Flow

**SCHEDULER**

* [ ] Create daemon to manage Minecraft instances
* [x] Metrics collecting
* [ ] Plug into docker-compose environment
* [ ] Secure redis instance by default
* [ ] Support redis clustering

**DASHBOARD**

* [ ] Fully-featured dashboard written with Vue.js 2
* [x] Login
* [ ] Account management
* [ ] Server management (Rancher-like?)
* [ ] File management (?)
* [ ] Metrics overview/details (?)
* [ ] WebSockets integration
* [ ] *optional* Basic SSO support
* [ ] All other API features once they are implemented.

Seems to be headed by @md678685, so I'll let him adjust this as needed!  
*Last edited by @md678685 - updated checklist to be more specific*

**BACKEND ARCH**

* [ ] Secure site-to-site VPN, for scheduler to API communication.
* [ ] Hardened redis
* [ ] *optional* Support ArangoDB clustering.

**MISC**

* [ ] Demo app for authentication workflow.

... more may be added at anytime!

**Comment by jaredallard** [comment]
@md678685 Going to move this to v6.0 project, and start migrating into issue tracking. I plan to track all issues on this repo (major ones anyways). Then aggregate minor ones in those said issues.

**Comment by mdcfe** [comment]
The architecture docs suggest that we're separating metrics collection from the core - is that the case?

**Comment by jaredallard** [comment]
Yes, metrics should be a last priority service that doesn't have time frames. Separating it allows us to not care about when metrics are processed
